version: "3.8"

x-app: &app
  build:
    context: .
  environment:
    RAILS_MASTER_KEY: $RAILS_MASTER_KEY
    RAILS_ENV: development
    REDIS_URL: redis://redis:6379
    TAPYRUS_AUTHORITY_KEY: cUJN5RVzYWFoeY8rUztd47jzXCu1p57Ay8V7pqCzsBD3PEXN7Dd4
    TAPYRUS_RPC_HOST: tapyrusd
    TAPYRUS_RPC_PORT: 12381
    TAPYRUS_RPC_USER: rpcuser
    TAPYRUS_RPC_PASSWORD: rpcpassword

services:
  web:
    <<: *app
    command: bundle exec rails server -p 3000 -b 0.0.0.0
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    depends_on:
      tapyrusd:
        condition: service_started
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 10s
      retries: 30
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"

  tapyrusd:
    image: tapyrus/tapyrusd:v0.5.1
    environment:
      GENESIS_BLOCK_WITH_SIG: 0100000000000000000000000000000000000000000000000000000000000000000000002b5331139c6bc8646bb4e5737c51378133f70b9712b75548cb3c05f9188670e7440d295e7300c5640730c4634402a3e66fb5d921f76b48d8972a484cc0361e66ef74f45e012103af80b90d25145da28c583359beb47b21796b2fe1a23c1511e443e7a64dfdb27d40e05f064662d6b9acf65ae416379d82e11a9b78cdeb3a316d1057cd2780e3727f70a61f901d10acbe349cd11e04aa6b4351e782c44670aefbe138e99a5ce75ace01010000000100000000000000000000000000000000000000000000000000000000000000000000000000ffffffff0100f2052a010000001976a91445d405b9ed450fec89044f9b7a99a4ef6fe2cd3f88ac00000000
    ports:
      - "12381:12381"
    volumes:
      - tapyrus:/var/lib/tapyrus

  sidekiq:
    <<: *app
    command: bin/bundle exec sidekiq -C config/sidekiq.yml
    depends_on:
      redis:
        condition: service_healthy
      web:
        condition: service_started
      db:
        condition: service_healthy

  redis:
    image: redis:latest
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 10s
      retries: 30
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

volumes:
  redis:
  tapyrus:
  db:
