version: "3.8"

x-app: &app
  build:
    context: .
    dockerfile: ./docker/web/Dockerfile
  environment:
    APP_HOST: $APP_HOST
    MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    RAILS_MASTER_KEY: $RAILS_MASTER_KEY
    RAILS_ENV: production
    REDIS_URL: redis://redis:6379
    TAPYRUS_AUTHORITY_KEY: cUJN5RVzYWFoeY8rUztd47jzXCu1p57Ay8V7pqCzsBD3PEXN7Dd4
    TAPYRUS_CHAIN_PARAMS: dev
    TAPYRUS_RPC_HOST: tapyrusd
    TAPYRUS_RPC_PORT: 12381
    TAPYRUS_RPC_USER: rpcuser
    TAPYRUS_RPC_PASSWORD: rpcpassword
    TZ: Asia/Tokyo
    WEBAUTHN_ORIGIN: $WEBAUTHN_ORIGIN
  depends_on:
    db:
      condition: service_healthy
    tapyrusd:
      condition: service_started
    redis:
      condition: service_healthy

services:
  web:
    <<: *app
    command: bin/bundle exec puma -C config/puma.rb
    healthcheck:
      test: [ "CMD", "curl" ,"127.0.0.1:3000" ]
      interval: 10s
      timeout: 10s
      retries: 30
    volumes:
      - public-data:/rails/public
      - tmp-data:/rails/tmp
      - log-data:/rails/log

  nginx:
    image: nginx:alpine
    environment:
      APP_HOST: $APP_HOST
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx:/etc/nginx/templates
      - certs:/etc/letsencrypt
      - certs-data:/var/lib/letsencrypt
      - public-data:/kokuten/public
      - tmp-data:/kokuten/tmp
    depends_on:
      web:
        condition: service_healthy

  db:
    image: mysql:8.0
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      TZ: Asia/Tokyo
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 10s
      retries: 30
    volumes:
      - db:/var/lib/mysql

  tapyrusd:
    image: tapyrus/tapyrusd:v0.5.1
    environment:
      GENESIS_BLOCK_WITH_SIG: 0100000000000000000000000000000000000000000000000000000000000000000000002b5331139c6bc8646bb4e5737c51378133f70b9712b75548cb3c05f9188670e7440d295e7300c5640730c4634402a3e66fb5d921f76b48d8972a484cc0361e66ef74f45e012103af80b90d25145da28c583359beb47b21796b2fe1a23c1511e443e7a64dfdb27d40e05f064662d6b9acf65ae416379d82e11a9b78cdeb3a316d1057cd2780e3727f70a61f901d10acbe349cd11e04aa6b4351e782c44670aefbe138e99a5ce75ace01010000000100000000000000000000000000000000000000000000000000000000000000000000000000ffffffff0100f2052a010000001976a91445d405b9ed450fec89044f9b7a99a4ef6fe2cd3f88ac00000000
      TZ: Asia/Tokyo
    volumes:
      - tapyrus:/var/lib/tapyrus

  sidekiq:
    <<: *app
    command: bin/bundle exec sidekiq -C config/sidekiq.yml
    depends_on:
      web:
        condition: service_healthy

  redis:
    image: redis:latest
    environment:
      TZ: Asia/Tokyo
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 10s
      retries: 30
    volumes:
      - redis:/data

volumes:
  redis:
  tapyrus:
  db:
  certs:
  certs-data:
  public-data:
  tmp-data:
  log-data:
